"""
StorageService — the object-storage contract, and its SeaweedFS implementation.

Everything that stores bytes goes through this interface. That is the point: the
alternative is S3 calls scattered across handlers, each with its own idea of how
a key is built, and one of them eventually builds a key from a filename.

    StorageService: put / get / head / delete / exists

Object-key design, which is the security-critical part
------------------------------------------------------
Keys are generated by the application from TRUSTED IDENTIFIERS ONLY — UUIDs that
came from the database or the auth layer. A filename never becomes part of a key.

    org/{org_id}/documents/{document_id}/original      organization-shared
    users/{user_id}/documents/{document_id}/original   private to one user

The original filename is preserved as object METADATA and in the Document row,
never in the path. This is deliberate: `/ingest/upload` currently does
`Path(f"data_vault/{user_id}/{file.filename}")` with no sanitisation, so a
filename of `../../x` escapes its directory. Reusing filesystem paths as object
keys would carry that flaw into the object store. Every key this module emits is
built from UUIDs and validated against a strict pattern before it is used.

ACL model, and how it maps onto the existing boundary
-----------------------------------------------------
The filesystem convention established in the Phase A audit is:

    data_vault/<file>            → organization-shared  (ingested as __org__)
    data_vault/<user_id>/<file>  → private to that user

That maps onto Postgres + object storage as:

    scope=org      sensitivity='internal'  key prefix org/{org_id}/…
    scope=private  sensitivity='private'   key prefix users/{user_id}/…

`documents.user_id` and `documents.org_id` are both NOT NULL with foreign keys,
so "__org__" cannot be a user_id — an organization document still records the
real curator who uploaded it, and `sensitivity` carries the scope. Ownership
therefore lives in the DATABASE, and the key prefix mirrors it for defence in
depth; neither is derived from the other at read time.
"""
from __future__ import annotations

import hashlib
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any, Optional, Protocol
from urllib.parse import quote

from .client import (S3Transport, StorageAuthError, StorageError, StorageNotFound,
                     StorageUnavailable, get_transport)

log = logging.getLogger("aria.storage")

# A generated key and nothing else. No dots, no traversal, no leading slash.
_KEY_RE = re.compile(r"^(org|users)/[0-9a-fA-F-]{8,36}/documents/[0-9a-fA-F-]{8,36}/[a-z0-9_.-]{1,64}$")
_UUID_RE = re.compile(r"^[0-9a-fA-F-]{8,36}$")

SCOPE_ORG = "org"
SCOPE_PRIVATE = "private"


class InvalidObjectKey(ValueError):
    """A key that was not generated by this module, or does not validate."""


def build_key(*, scope: str, owner_id: str, document_id: str,
              variant: str = "original") -> str:
    """The one place an object key is constructed.

    `owner_id` is org_id for scope=org and user_id for scope=private. Both must
    be UUID-shaped; `variant` is a fixed vocabulary, never user input.
    """
    if scope not in (SCOPE_ORG, SCOPE_PRIVATE):
        raise InvalidObjectKey(f"unknown scope {scope!r}")
    if not _UUID_RE.match(str(owner_id or "")):
        raise InvalidObjectKey("owner_id must be a UUID — refusing to build a key from it")
    if not _UUID_RE.match(str(document_id or "")):
        raise InvalidObjectKey("document_id must be a UUID")
    if not re.fullmatch(r"[a-z0-9_.-]{1,64}", variant or ""):
        raise InvalidObjectKey(f"invalid variant {variant!r}")
    prefix = "org" if scope == SCOPE_ORG else "users"
    key = f"{prefix}/{owner_id}/documents/{document_id}/{variant}"
    return validate_key(key)


def validate_key(key: str) -> str:
    """Reject anything that is not an application-generated key.

    Called on the way IN (build_key) and again on the way OUT (before any request
    is signed), so a key that reached the store by some other route — a client
    parameter, a stale DB row — cannot be used to read outside its prefix.
    """
    k = str(key or "")
    if ".." in k or k.startswith("/") or "//" in k or "\\" in k:
        raise InvalidObjectKey("key contains traversal or an absolute path")
    if not _KEY_RE.match(k):
        raise InvalidObjectKey(f"key does not match the generated-key pattern: {k[:80]!r}")
    return k


def key_is_owned_by(key: str, *, scope: str, owner_id: str) -> bool:
    """Does this key belong under the given owner's prefix?

    Used as a second check at download time. The database is the authority on
    ownership; this catches a row whose uri was written for a different owner.
    """
    try:
        validate_key(key)
    except InvalidObjectKey:
        return False
    prefix = f"{'org' if scope == SCOPE_ORG else 'users'}/{owner_id}/"
    return key.startswith(prefix)


@dataclass(slots=True)
class ObjectMeta:
    key: str
    size: int
    content_type: Optional[str] = None
    etag: Optional[str] = None
    last_modified: Optional[str] = None
    metadata: dict[str, str] = field(default_factory=dict)


class StorageService(Protocol):
    """The contract. Implementations must not leak transport details."""

    def put(self, key: str, data: bytes, *, content_type: str = ...,
            metadata: Optional[dict] = ...) -> ObjectMeta: ...
    def get(self, key: str) -> bytes: ...
    def head(self, key: str) -> ObjectMeta: ...
    def delete(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...


class SeaweedFSStorage:
    """StorageService over the authenticated SeaweedFS S3 gateway.

    Never talks to the Filer: the Filer is unauthenticated and is bound to
    loopback precisely because it bypasses bucket ACLs. All access is SigV4
    through :8333 so the per-bucket identity is enforced on every call.
    """

    def __init__(self, transport: Optional[S3Transport] = None,
                 bucket: Optional[str] = None) -> None:
        self._t = transport or get_transport()
        if bucket is None:
            from config.settings import SEAWEEDFS_BUCKET_NAME
            bucket = SEAWEEDFS_BUCKET_NAME
        self._bucket = bucket

    def _path(self, key: str) -> str:
        return f"/{self._bucket}/{validate_key(key)}"

    @property
    def bucket(self) -> str:
        return self._bucket

    @property
    def configured(self) -> bool:
        return self._t.configured

    # ── writes ───────────────────────────────────────────────────────────────

    def put(self, key: str, data: bytes, *, content_type: str = "application/octet-stream",
            metadata: Optional[dict] = None) -> ObjectMeta:
        """Store bytes. Returns metadata read back from the store, not echoed input."""
        extra = {"Content-Type": content_type}
        for k, v in (metadata or {}).items():
            # Header-safe only: metadata values travel as HTTP headers, and an
            # embedded newline would let a filename inject a header.
            safe = re.sub(r"[^\x20-\x7e]", "", str(v))[:256]
            extra[f"x-amz-meta-{re.sub(r'[^a-z0-9-]', '-', k.lower())}"] = safe
        t0 = time.monotonic()
        self._t.request("PUT", self._path(key), payload=data, extra=extra)
        log.info("storage put %s (%d bytes) in %.0fms", key, len(data),
                 (time.monotonic() - t0) * 1000)
        return self.head(key)

    def delete(self, key: str) -> bool:
        r = self._t.request("DELETE", self._path(key), raise_for_status=False)
        if r.status_code in (401, 403):
            raise StorageAuthError(f"not permitted to delete {key}")
        return r.status_code in (200, 204)

    # ── reads ────────────────────────────────────────────────────────────────

    def get(self, key: str) -> bytes:
        return self._t.request("GET", self._path(key)).content

    def head(self, key: str) -> ObjectMeta:
        r = self._t.request("HEAD", self._path(key))
        meta = {k[len("x-amz-meta-"):]: v for k, v in r.headers.items()
                if k.lower().startswith("x-amz-meta-")}
        return ObjectMeta(key=key, size=int(r.headers.get("content-length") or 0),
                          content_type=r.headers.get("content-type"),
                          etag=(r.headers.get("etag") or "").strip('"') or None,
                          last_modified=r.headers.get("last-modified"),
                          metadata=meta)

    def exists(self, key: str) -> bool:
        try:
            self.head(key)
            return True
        except StorageNotFound:
            return False

    # ── listing, for reconciliation only ─────────────────────────────────────

    def list_keys(self, prefix: str = "", limit: int = 1000) -> list[str]:
        """Keys under a prefix. Used by the reconciliation report, not by request
        handlers — a handler should resolve a key from the database, never by
        searching the bucket."""
        q = f"list-type=2&max-keys={int(limit)}"
        if prefix:
            q += f"&prefix={quote(prefix, safe='/')}"
        r = self._t.request("GET", f"/{self._bucket}/", query=q)
        return re.findall(r"<Key>([^<]+)</Key>", r.text)

    def health(self) -> dict:
        """Signed HEAD on the bucket: proves reachability AND credentials."""
        t0 = time.monotonic()
        try:
            r = self._t.request("HEAD", f"/{self._bucket}/", raise_for_status=False)
            ms = round((time.monotonic() - t0) * 1000, 1)
            if r.status_code in (401, 403):
                return {"status": "auth_failure", "latency_ms": ms,
                        "detail": "gateway rejected a signed request"}
            if r.status_code == 404:
                return {"status": "auth_failure", "latency_ms": ms,
                        "detail": f"bucket {self._bucket!r} does not exist"}
            return {"status": "ok" if r.status_code < 400 else "unreachable",
                    "latency_ms": ms, "bucket": self._bucket,
                    "http_status": r.status_code}
        except StorageUnavailable as e:
            return {"status": "unreachable", "detail": str(e)[:160]}
        except StorageError as e:
            return {"status": "auth_failure", "detail": str(e)[:160]}


_default: Optional[SeaweedFSStorage] = None


def get_storage() -> SeaweedFSStorage:
    """Shared instance. Construction opens no socket, so this is safe to call
    even when SeaweedFS is down."""
    global _default
    if _default is None:
        _default = SeaweedFSStorage()
    return _default


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()
