"""chat message/artifact persistence + long-term memory

Revision ID: c1a7f0b2e9d4
Revises: 63dd5dbff722
Create Date: 2026-08-01

Hand-written (not autogenerated: the model tree has pre-existing drift against the
database, so autogenerate would emit unrelated destructive operations).

Purely additive — three new tables plus defaulted columns on chat_sessions. The
running service does not reference any of it, so this can be applied with no restart
and no downtime.

Why: message bodies previously lived in flat JSON files capped at 24 turns and could
only store {role, content, ts}. That made durable threads impossible and silently
destroyed history. chat_messages + chat_artifacts make a conversation replayable
exactly as rendered (charts/tables/PDFs included); memory_items backs cross-thread
recall with Postgres as the system of record and Qdrant as the vector index.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "c1a7f0b2e9d4"
down_revision = "63dd5dbff722"
branch_labels = None
depends_on = None

_JSONB = postgresql.JSONB(astext_type=sa.Text())
_UUID = postgresql.UUID(as_uuid=True)


def _ts_cols() -> list[sa.Column]:
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    ]


def upgrade() -> None:
    # ── chat_sessions: additive columns (all defaulted → no table rewrite) ────────
    op.add_column("chat_sessions", sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("chat_sessions", sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("chat_sessions", sa.Column("kind", sa.Text(), server_default=sa.text("'assistant'"), nullable=False))
    op.add_column("chat_sessions", sa.Column("board_id", sa.Text(), nullable=True))
    op.add_column("chat_sessions", sa.Column("last_message_preview", sa.Text(), nullable=True))
    op.add_column("chat_sessions", sa.Column("artifact_count", sa.Integer(), server_default=sa.text("0"), nullable=False))
    op.create_index("ix_chat_sessions_user_pinned", "chat_sessions",
                    ["user_id", "pinned", "last_message_at"],
                    postgresql_where=sa.text("deleted_at IS NULL"))
    # One board per session, per user. Partial so soft-deleted rows don't block reuse.
    op.create_index("uq_chat_sessions_board", "chat_sessions", ["user_id", "board_id"], unique=True,
                    postgresql_where=sa.text("board_id IS NOT NULL AND deleted_at IS NULL"))

    # ── chat_messages ────────────────────────────────────────────────────────────
    op.create_table(
        "chat_messages",
        sa.Column("id", _UUID, server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", _UUID, nullable=True),
        sa.Column("user_id", _UUID, nullable=False),
        sa.Column("session_id", _UUID, nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'complete'"), nullable=False),
        sa.Column("agent", sa.Text(), nullable=True),
        sa.Column("model_key", sa.Text(), nullable=True),
        sa.Column("tool_calls", _JSONB, server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=True),
        sa.Column("pipeline", _JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("tokens_in", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_micros", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("meta", _JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        *_ts_cols(),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        # Makes the JSON backfill (and any retry) idempotent via ON CONFLICT DO NOTHING.
        sa.UniqueConstraint("session_id", "seq", name="uq_chat_messages_session_seq"),
    )
    op.create_index("ix_chat_messages_org_id", "chat_messages", ["org_id"])
    op.create_index("ix_chat_messages_user_id", "chat_messages", ["user_id"])
    op.create_index("ix_chat_messages_session_id", "chat_messages", ["session_id"])
    op.create_index("ix_chat_messages_session_seq", "chat_messages", ["session_id", "seq"])
    op.create_index("ix_chat_messages_user_created", "chat_messages", ["user_id", "created_at"])

    # ── chat_artifacts ───────────────────────────────────────────────────────────
    op.create_table(
        "chat_artifacts",
        sa.Column("id", _UUID, server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", _UUID, nullable=True),
        sa.Column("user_id", _UUID, nullable=False),
        sa.Column("session_id", _UUID, nullable=False),
        sa.Column("message_id", _UUID, nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        # spec = how to reproduce it; data = the snapshot the user actually saw.
        sa.Column("spec", _JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("data", _JSONB, nullable=True),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("meta", _JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        *_ts_cols(),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["chat_messages.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_chat_artifacts_org_id", "chat_artifacts", ["org_id"])
    op.create_index("ix_chat_artifacts_user_id", "chat_artifacts", ["user_id"])
    op.create_index("ix_chat_artifacts_session_id", "chat_artifacts", ["session_id"])
    op.create_index("ix_chat_artifacts_message_id", "chat_artifacts", ["message_id"])
    op.create_index("ix_chat_artifacts_session", "chat_artifacts", ["session_id", "created_at"])

    # ── memory_items ─────────────────────────────────────────────────────────────
    op.create_table(
        "memory_items",
        sa.Column("id", _UUID, server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", _UUID, nullable=True),
        sa.Column("user_id", _UUID, nullable=False),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("fact_norm", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), server_default=sa.text("'fact'"), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'auto'"), nullable=False),
        sa.Column("source_session_id", _UUID, nullable=True),
        sa.Column("confidence", sa.Float(), server_default=sa.text("0.6"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("superseded_by", _UUID, nullable=True),
        sa.Column("vector_id", _UUID, nullable=True),
        sa.Column("use_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", _JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        *_ts_cols(),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_session_id"], ["chat_sessions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["superseded_by"], ["memory_items.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_memory_items_org_id", "memory_items", ["org_id"])
    op.create_index("ix_memory_items_user_id", "memory_items", ["user_id"])
    # Exact-duplicate guard: same normalised fact can only be active once per user.
    op.create_index("uq_memory_user_factnorm", "memory_items", ["user_id", "fact_norm"], unique=True,
                    postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.create_index("ix_memory_user_status", "memory_items", ["user_id", "status", "updated_at"])


def downgrade() -> None:
    op.drop_table("memory_items")
    op.drop_table("chat_artifacts")
    op.drop_table("chat_messages")
    op.drop_index("uq_chat_sessions_board", table_name="chat_sessions")
    op.drop_index("ix_chat_sessions_user_pinned", table_name="chat_sessions")
    for col in ("artifact_count", "last_message_preview", "board_id", "kind", "pinned_at", "pinned"):
        op.drop_column("chat_sessions", col)
